server {
    server_name develop.harembrasil.com.br;
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    access_log /var/www/vhosts/develop.harembrasil.com.br/logs/access.log;
    error_log  /var/www/vhosts/develop.harembrasil.com.br/logs/error.log;

    client_max_body_size 32m;

    root /var/www/vhosts/develop.harembrasil.com.br;
    index index.html;

    location /api/ {
        proxy_pass         http://127.0.0.1:41082/;
        proxy_http_version 1.1;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/vhosts/develop.harembrasil.com.br/;
        try_files $uri =404;
    }

    ssl_certificate     /etc/letsencrypt/live/develop.harembrasil.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/develop.harembrasil.com.br/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = develop.harembrasil.com.br) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name develop.harembrasil.com.br;
    return 404;
}
